/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import Objetos.ClienteFisico;
import br.com.parg.viacep.ViaCEP;
import br.com.parg.viacep.ViaCEPException;
import conexao.ConectaBanco;
import conexao.InsereNoBanco;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import javafx.scene.layout.Border;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Manoel Henrique
 */
public class CadastrarClienteF extends javax.swing.JFrame {

    ClienteFisico clienteFisico = new ClienteFisico();
    conexao.ConectaBanco conecta = new ConectaBanco();
    conexao.InsereNoBanco insere = new InsereNoBanco();
    Jframes.ImagemArray pegarImagem = new ImagemArray();
    
     BufferedImage imageBuffer = null;
     ByteArrayOutputStream bytesImg = new ByteArrayOutputStream();
     byte[] byteArray;
     
    Image img;
    public CadastrarClienteF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo1 = new javax.swing.JPanel();
        campoTelefone = new javax.swing.JFormattedTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoCpf = new javax.swing.JFormattedTextField();
        campoRg = new javax.swing.JFormattedTextField();
        campoDataNascimento = new javax.swing.JFormattedTextField();
        campoCep = new javax.swing.JFormattedTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        campoCtps = new javax.swing.JFormattedTextField();
        campoUfCtps = new javax.swing.JComboBox<>();
        campoSerie = new javax.swing.JFormattedTextField();
        campoEstadoCivil = new javax.swing.JComboBox<>();
        campoPis = new javax.swing.JFormattedTextField();
        jLabel70 = new javax.swing.JLabel();
        campoRua = new javax.swing.JTextField();
        LabelCertidaoCasamento = new javax.swing.JLabel();
        campoCertidaoCasamento = new javax.swing.JFormattedTextField();
        cadastrarPessoaFisica = new javax.swing.JButton();
        campoConjuge = new javax.swing.JTextField();
        LabelConjuge = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoUf = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        selecionarImagemPF = new javax.swing.JButton();
        Novo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        imagemPF = new javax.swing.JLabel();
        clientes = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar cliente: Pessoa física");
        setResizable(false);

        fundo1.setEnabled(false);

        try {
            campoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelefone.setEnabled(false);

        jLabel59.setText("Nome");

        jLabel60.setText("Data de nascimento");

        jLabel61.setText("CPF");

        jLabel62.setText("CEP");

        jLabel63.setText("RG");

        jLabel64.setText("Telefone");

        jLabel65.setText("PIS");

        campoNome.setEnabled(false);
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });

        try {
            campoCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCpf.setEnabled(false);
        campoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpfActionPerformed(evt);
            }
        });

        try {
            campoRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoRg.setEnabled(false);
        campoRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRgActionPerformed(evt);
            }
        });

        try {
            campoDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoDataNascimento.setEnabled(false);
        campoDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataNascimentoActionPerformed(evt);
            }
        });

        try {
            campoCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCep.setEnabled(false);
        campoCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCepActionPerformed(evt);
            }
        });
        campoCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoCepKeyReleased(evt);
            }
        });

        jLabel66.setText("Série");

        jLabel67.setText("CTPS");

        jLabel68.setText("UF da CTPS");

        jLabel69.setText("Estado civil");

        try {
            campoCtps.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCtps.setEnabled(false);

        campoUfCtps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        campoUfCtps.setEnabled(false);
        campoUfCtps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUfCtpsActionPerformed(evt);
            }
        });

        try {
            campoSerie.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoSerie.setEnabled(false);

        campoEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Solteiro", "Casado", "Divorciado" }));
        campoEstadoCivil.setEnabled(false);
        campoEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEstadoCivilActionPerformed(evt);
            }
        });

        try {
            campoPis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.#####.##-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoPis.setEnabled(false);
        campoPis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPisActionPerformed(evt);
            }
        });

        jLabel70.setText("Rua");

        campoRua.setEnabled(false);

        LabelCertidaoCasamento.setText("Certidão de casamento");

        try {
            campoCertidaoCasamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###### ## ## #### # ##### ### ####### ## ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCertidaoCasamento.setEnabled(false);
        campoCertidaoCasamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCertidaoCasamentoActionPerformed(evt);
            }
        });

        cadastrarPessoaFisica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/salvar.png"))); // NOI18N
        cadastrarPessoaFisica.setEnabled(false);
        cadastrarPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPessoaFisicaActionPerformed(evt);
            }
        });

        campoConjuge.setEnabled(false);
        campoConjuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoConjugeActionPerformed(evt);
            }
        });

        LabelConjuge.setText("Nome do cônjuge");

        campoCidade.setEnabled(false);
        campoCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCidadeActionPerformed(evt);
            }
        });

        jLabel2.setText("Cidade");

        campoN.setEnabled(false);

        jLabel3.setText("Nº");

        campoUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        campoUf.setEnabled(false);

        jLabel1.setText("UF");

        selecionarImagemPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/add_foto.png"))); // NOI18N
        selecionarImagemPF.setEnabled(false);
        selecionarImagemPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarImagemPFActionPerformed(evt);
            }
        });

        Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/novo.png"))); // NOI18N
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        imagemPF.setForeground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagemPF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagemPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );

        clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/usuarios.jpg"))); // NOI18N
        clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientesMouseEntered(evt);
            }
        });
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fundo1Layout = new javax.swing.GroupLayout(fundo1);
        fundo1.setLayout(fundo1Layout);
        fundo1Layout.setHorizontalGroup(
            fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundo1Layout.createSequentialGroup()
                        .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(LabelCertidaoCasamento)
                        .addGap(172, 172, 172))
                    .addGroup(fundo1Layout.createSequentialGroup()
                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundo1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(campoDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(193, 193, 193))
                            .addGroup(fundo1Layout.createSequentialGroup()
                                .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(100, 100, 100)))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundo1Layout.createSequentialGroup()
                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(fundo1Layout.createSequentialGroup()
                                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addComponent(cadastrarPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campoN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(selecionarImagemPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)))
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addComponent(campoUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fundo1Layout.createSequentialGroup()
                                .addComponent(campoRua)
                                .addGap(18, 18, 18)
                                .addComponent(campoCertidaoCasamento, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fundo1Layout.createSequentialGroup()
                                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(231, 231, 231)))
                                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(111, 111, 111))
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(35, 35, 35))
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addComponent(campoEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(fundo1Layout.createSequentialGroup()
                                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoCep, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoRg)
                                            .addGroup(fundo1Layout.createSequentialGroup()
                                                .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(72, 72, 72)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoTelefone)
                                            .addGroup(fundo1Layout.createSequentialGroup()
                                                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoCtps)
                                            .addGroup(fundo1Layout.createSequentialGroup()
                                                .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(50, 50, 50)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoSerie)
                                            .addGroup(fundo1Layout.createSequentialGroup()
                                                .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(20, 20, 20)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(campoUfCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(fundo1Layout.createSequentialGroup()
                                                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(76, 76, 76))
                                            .addComponent(campoPis)))
                                    .addGroup(fundo1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoConjuge, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LabelConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(28, 28, 28))))
        );
        fundo1Layout.setVerticalGroup(
            fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundo1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(jLabel69)
                    .addComponent(jLabel59))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundo1Layout.createSequentialGroup()
                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel64)
                                .addComponent(jLabel67)
                                .addComponent(jLabel63))
                            .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel68)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoUfCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fundo1Layout.createSequentialGroup()
                        .addComponent(jLabel65)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundo1Layout.createSequentialGroup()
                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundo1Layout.createSequentialGroup()
                                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fundo1Layout.createSequentialGroup()
                                .addComponent(LabelConjuge)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelCertidaoCasamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCertidaoCasamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundo1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selecionarImagemPF, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadastrarPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(fundo1Layout.createSequentialGroup()
                                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(fundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(fundo1Layout.createSequentialGroup()
                            .addComponent(jLabel62)
                            .addGap(26, 26, 26))
                        .addComponent(campoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setText("Cadastrar cliente: Pessoa física");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(fundo1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel58)
                .addGap(18, 18, 18)
                .addComponent(fundo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCpfActionPerformed

    private void campoRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRgActionPerformed

    private void campoDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataNascimentoActionPerformed

    private void campoCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCepActionPerformed

    }//GEN-LAST:event_campoCepActionPerformed

    private void campoCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCepKeyReleased
        String cp = campoCep.getText();
        cp = cp.replaceAll("\\D*", ""); //ignora qualquer coisa que não seja número
        int cont = cp.length();
        ViaCEP viaCep = new ViaCEP();

        if(cont==8){
            try {
                viaCep.buscar(cp);
                campoCidade.setText(viaCep.getLocalidade());
                campoRua.setText(viaCep.getLogradouro());
                campoUf.setSelectedItem(viaCep.getUf());
            } catch (ViaCEPException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao buscar cep"+ex);
            }
        }
    }//GEN-LAST:event_campoCepKeyReleased

    private void campoUfCtpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUfCtpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUfCtpsActionPerformed

    private void campoEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEstadoCivilActionPerformed
        if(campoEstadoCivil.getSelectedItem().equals("Casado")){
            campoConjuge.setEnabled(true);
            campoCertidaoCasamento.setEnabled(true);
        }
        else{
            campoConjuge.setText("");
            campoCertidaoCasamento.setText("");
            campoConjuge.setEnabled(false);
            campoCertidaoCasamento.setEnabled(false);
        }
    }//GEN-LAST:event_campoEstadoCivilActionPerformed

    private void campoPisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPisActionPerformed

    private void campoCertidaoCasamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCertidaoCasamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCertidaoCasamentoActionPerformed

    private void cadastrarPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPessoaFisicaActionPerformed

        conecta.conecta();

        pegarImagem.setImagem(byteArray);
        //insere dados no banco
        clienteFisico.setNome(campoNome.getText());
        clienteFisico.setCPF(campoCpf.getText());
        clienteFisico.setEstadoCivil((String)campoEstadoCivil.getSelectedItem());
        clienteFisico.setRG(campoRg.getText());
        clienteFisico.setTelefone(campoTelefone.getText());
        clienteFisico.setCTPS(campoCtps.getText());
        clienteFisico.setSerieCtps(campoSerie.getText());
        clienteFisico.setUFdaCTPS((String)campoUfCtps.getSelectedItem());
        clienteFisico.setPIS(campoPis.getText());
        clienteFisico.setDataNascimento(campoDataNascimento.getText());
        clienteFisico.setCEP(campoCep.getText());
        clienteFisico.setConjuge(campoConjuge.getText());
        clienteFisico.setRua(campoRua.getText());
        clienteFisico.setCertidaoCamento(campoCertidaoCasamento.getText());
        clienteFisico.setNumero(campoN.getText());
        clienteFisico.setCidade(campoCidade.getText());
        clienteFisico.setUF((String)campoUf.getSelectedItem());
        clienteFisico.setFoto(pegarImagem.getImagem());

        // converte a foto em byte[]
        // clienteFisico.setFotoCF(imagem.ConverteImg.getImgBytes(foto));
        if(insere.inserirClienteF(clienteFisico)==true){
            //zera os campos depois de salvos os dados

            campoNome.setText(null);
            campoCpf.setText(null);
            campoEstadoCivil.setSelectedIndex(0);
            campoRg.setText(null);
            campoTelefone.setText(null);
            campoCtps.setText(null);
            campoSerie.setText(null);
            campoUfCtps.setSelectedIndex(0);
            campoPis.setText(null);
            campoDataNascimento.setText(null);
            campoCep.setText(null);
            campoConjuge.setText(null);
            campoRua.setText(null);
            campoCertidaoCasamento.setText(null);
            campoN.setText(null);
            campoCidade.setText(null);
            campoUf.setSelectedIndex(0);
            imagemPF.setIcon(null);
            //imagemPF.remove(pegarImagem);
            
         //desativa os campos   
        Novo.setEnabled(true);
        campoNome.setEnabled(false);
        campoCpf.setEnabled(false);
        campoEstadoCivil.setEnabled(false);
        campoRg.setEnabled(false);
        campoTelefone.setEnabled(false);
        campoCtps.setEnabled(false);
        campoSerie.setEnabled(false);
        campoPis.setEnabled(false);
        campoUfCtps.setEnabled(false);
        campoDataNascimento.setEnabled(false);
        campoCep.setEnabled(false);
        campoRua.setEnabled(false);
        campoN.setEnabled(false);
        campoCidade.setEnabled(false);
        campoUf.setEnabled(false);
        selecionarImagemPF.setEnabled(false);
        cadastrarPessoaFisica.setEnabled(false);

        }
        else{
            JOptionPane.showMessageDialog(null,"Não é possível cadastrar o cliente físico\n"
                + "Verifique se todos os campos estão preenchidos");
        }

    }//GEN-LAST:event_cadastrarPessoaFisicaActionPerformed

    private void campoConjugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoConjugeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoConjugeActionPerformed

    private void campoCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCidadeActionPerformed

    private void selecionarImagemPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarImagemPFActionPerformed
        //                //Inserindo imagem no Jlabel
        //                JFileChooser arquivo = new JFileChooser();
        //                arquivo.setDialogTitle("selecionar imagem");
        //                arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //
        //                FileNameExtensionFilter tipoArquivo = new FileNameExtensionFilter("Imagem", "jpg","png");
        //
        //                arquivo.setFileFilter(tipoArquivo);
        //                int retorno =  arquivo.showOpenDialog(this);
        //
        //                if(retorno == JFileChooser.APPROVE_OPTION){
            //
            //                     File file = arquivo.getSelectedFile();
            //                     //código que redimeciona a imagem no Jlabel
            //                     ImageIcon imagem = new ImageIcon(file.getPath());
            //                     //--------------------------------------------------------------------------------------------------------------------------Image img = imagem.getImage().getScaledInstance(imagemPJ.getWidth(), imagemPJ.getHeight(), Image.SCALE_DEFAULT);
            //                   img = imagem.getImage().getScaledInstance(imagemPF.getWidth(), imagemPF.getHeight(), Image.SCALE_DEFAULT);
            //                    //fim do código  que redimeciona a imagem no Jlabel
            //                     imagemPF.setIcon(new ImageIcon(img));
            //                    }
        //                //arquivo.showSaveDialog(this);
        //
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagens em JPEG e PNG","jpg","png");
        jfc.addChoosableFileFilter(filtro);
        jfc.setAcceptAllFileFilterUsed(false);
        jfc.setDialogTitle("Selecionar Foto");
        boolean isPng = false;

        jfc.showOpenDialog(imagemPF);

        if(jfc.getSelectedFile() != null)
        {
            String caminho = ""+jfc.getSelectedFile().getAbsolutePath();
            isPng = jfc.getSelectedFile().getName().endsWith("png");

            try {
                imageBuffer = ImageIO.read(new File(caminho));
                int type = BufferedImage.TYPE_INT_RGB;
                if(isPng){
                    type = BufferedImage.BITMASK;
                }

                BufferedImage redimensionarImagem = new BufferedImage(imagemPF.getWidth(), imagemPF.getHeight(), type);
                Graphics2D g = redimensionarImagem.createGraphics();
                g.setComposite(AlphaComposite.Src);
                g.drawImage(imageBuffer, 0, 0, imagemPF.getWidth(), imagemPF.getHeight(), null);

                if(isPng){
                    ImageIO.write(redimensionarImagem,"png", bytesImg);
                }
                else{
                    ImageIO.write(redimensionarImagem,"jpg", bytesImg);
                }

                bytesImg.flush();
                byteArray = bytesImg.toByteArray();
                bytesImg.close();

                Image imag = imageBuffer.getScaledInstance(imagemPF.getWidth(), imagemPF.getHeight(), Image.SCALE_SMOOTH);

                imagemPF.setBorder(null);
                imagemPF.setIcon(new ImageIcon(imag));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null,"Erro em carregar Imagem no JChosserFile \n Erro: "+ex);
            }
        }
    }//GEN-LAST:event_selecionarImagemPFActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        Novo.setEnabled(false);
        campoNome.setEnabled(true);
        campoCpf.setEnabled(true);
        campoEstadoCivil.setEnabled(true);
        campoRg.setEnabled(true);
        campoTelefone.setEnabled(true);
        campoCtps.setEnabled(true);
        campoSerie.setEnabled(true);
        campoPis.setEnabled(true);
        campoUfCtps.setEnabled(true);
        campoDataNascimento.setEnabled(true);
        campoCep.setEnabled(true);
        campoRua.setEnabled(true);
        campoN.setEnabled(true);
        campoCidade.setEnabled(true);
        campoUf.setEnabled(true);
        selecionarImagemPF.setEnabled(true);
        cadastrarPessoaFisica.setEnabled(true);
        
        imagemPF.setIcon(null);
            imagemPF.setBorder(BorderFactory.createLineBorder(Color.black, WIDTH));
           //imagemPF.setBorder(BorderFactory.createTitledBorder(imagemPF, "Foto", TitledBorder.CENTER, TitledBorder.TOP, imagemPF.setFont("XPImageBorder"), Color.black));
            //imagemPF.setBorder(BorderFactory.createTitledBorder

    }//GEN-LAST:event_NovoActionPerformed

    private void clientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesMouseEntered

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        ListarClientesFisicos LCF = new ListarClientesFisicos();
        LCF.setVisible(true);
    }//GEN-LAST:event_clientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarClienteF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCertidaoCasamento;
    private javax.swing.JLabel LabelConjuge;
    private javax.swing.JButton Novo;
    private javax.swing.JButton cadastrarPessoaFisica;
    private javax.swing.JFormattedTextField campoCep;
    private javax.swing.JFormattedTextField campoCertidaoCasamento;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoConjuge;
    private javax.swing.JFormattedTextField campoCpf;
    private javax.swing.JFormattedTextField campoCtps;
    private javax.swing.JFormattedTextField campoDataNascimento;
    private javax.swing.JComboBox<String> campoEstadoCivil;
    private javax.swing.JTextField campoN;
    private javax.swing.JTextField campoNome;
    private javax.swing.JFormattedTextField campoPis;
    private javax.swing.JFormattedTextField campoRg;
    private javax.swing.JTextField campoRua;
    private javax.swing.JFormattedTextField campoSerie;
    private javax.swing.JFormattedTextField campoTelefone;
    private javax.swing.JComboBox<String> campoUf;
    private javax.swing.JComboBox<String> campoUfCtps;
    private javax.swing.JButton clientes;
    private javax.swing.JPanel fundo1;
    private javax.swing.JLabel imagemPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton selecionarImagemPF;
    // End of variables declaration//GEN-END:variables
}
