/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import Objetos.ClienteJuridico;
import br.com.parg.viacep.ViaCEP;
import br.com.parg.viacep.ViaCEPException;
import conexao.ConectaBanco;
import conexao.InsereNoBanco;
import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Manoel Henrique
 */
public class CadastrarClienteJ extends javax.swing.JFrame {

    Jframes.ImagemArray pegarImagem = new ImagemArray();
    BufferedImage imageBuffer = null;
    ByteArrayOutputStream bytesImg = new ByteArrayOutputStream();
    byte[] byteArray;
    
    conexao.ConectaBanco conecta = new ConectaBanco();
    ClienteJuridico clienteJuridico = new ClienteJuridico();
    InsereNoBanco insere = new InsereNoBanco();
    Image img;
    public CadastrarClienteJ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        fundo2 = new javax.swing.JPanel();
        campoNomeFantasia = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        campoCnpj = new javax.swing.JFormattedTextField();
        campoRazaoSocial = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        campoCep2 = new javax.swing.JFormattedTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        campoRua2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoAreaAtuacao = new javax.swing.JComboBox<>();
        campoCidade2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoN2 = new javax.swing.JTextField();
        cadastrarPessoaJuridica = new javax.swing.JButton();
        campoTelefone2 = new javax.swing.JFormattedTextField();
        jLabel73 = new javax.swing.JLabel();
        selecionarImagemPJ = new javax.swing.JButton();
        Novo = new javax.swing.JButton();
        campoUf = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        imagemPJ = new javax.swing.JLabel();
        clientes = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar cliente: Pessoa jurídica");
        setResizable(false);

        campoNomeFantasia.setEnabled(false);
        campoNomeFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeFantasiaActionPerformed(evt);
            }
        });
        campoNomeFantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNomeFantasiaKeyReleased(evt);
            }
        });

        jLabel56.setText("Nome fantasia");

        jLabel24.setText("CNPJ");

        try {
            campoCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCnpj.setEnabled(false);
        campoCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCnpjActionPerformed(evt);
            }
        });
        campoCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoCnpjKeyReleased(evt);
            }
        });

        campoRazaoSocial.setEnabled(false);
        campoRazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRazaoSocialActionPerformed(evt);
            }
        });
        campoRazaoSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoRazaoSocialKeyReleased(evt);
            }
        });

        jLabel57.setText("Razão social");

        try {
            campoCep2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCep2.setEnabled(false);
        campoCep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCep2ActionPerformed(evt);
            }
        });
        campoCep2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoCep2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoCep2KeyReleased(evt);
            }
        });

        jLabel71.setText("CEP");

        jLabel72.setText("Rua");

        campoRua2.setEnabled(false);
        campoRua2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoRua2KeyReleased(evt);
            }
        });

        jLabel4.setText("Área de atuação");

        campoAreaAtuacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Administração", "Agrícola", "Atacadista", "Comércio de roupas", "Comércio de sapatos", "Comécio peças auto.", "Contabilidade", "Educação", "Educação superior", "Engenharia civil", "E-commerce", "Farmacêutico", "Industrial", "Móveis e eletro", "Perfumaria", "Serviços alimenticios", "Serviços gerais", "Transporte público", "Universitária", "Varejo", " " }));
        campoAreaAtuacao.setEnabled(false);
        campoAreaAtuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAreaAtuacaoActionPerformed(evt);
            }
        });

        campoCidade2.setEnabled(false);
        campoCidade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCidade2ActionPerformed(evt);
            }
        });
        campoCidade2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoCidade2KeyReleased(evt);
            }
        });

        jLabel5.setText("Cidade");

        jLabel6.setText("Nº");

        campoN2.setEnabled(false);
        campoN2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoN2KeyReleased(evt);
            }
        });

        cadastrarPessoaJuridica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/salvar.png"))); // NOI18N
        cadastrarPessoaJuridica.setEnabled(false);
        cadastrarPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPessoaJuridicaActionPerformed(evt);
            }
        });

        try {
            campoTelefone2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelefone2.setEnabled(false);
        campoTelefone2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoTelefone2KeyReleased(evt);
            }
        });

        jLabel73.setText("Telefone");

        selecionarImagemPJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/add_foto.png"))); // NOI18N
        selecionarImagemPJ.setEnabled(false);
        selecionarImagemPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarImagemPJActionPerformed(evt);
            }
        });

        Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/novo.png"))); // NOI18N
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });

        campoUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        campoUf.setEnabled(false);
        campoUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUfActionPerformed(evt);
            }
        });

        jLabel1.setText("Uf");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        imagemPJ.setForeground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagemPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imagemPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/usuarios.jpg"))); // NOI18N
        clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientesMouseEntered(evt);
            }
        });
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fundo2Layout = new javax.swing.GroupLayout(fundo2);
        fundo2.setLayout(fundo2Layout);
        fundo2Layout.setHorizontalGroup(
            fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundo2Layout.createSequentialGroup()
                        .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(fundo2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNomeFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(campoRazaoSocial)
                            .addComponent(campoRua2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundo2Layout.createSequentialGroup()
                                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(campoN2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(fundo2Layout.createSequentialGroup()
                                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(campoCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 60, Short.MAX_VALUE))
                            .addGroup(fundo2Layout.createSequentialGroup()
                                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(fundo2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(fundo2Layout.createSequentialGroup()
                                        .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoCep2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoAreaAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(fundo2Layout.createSequentialGroup()
                        .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTelefone2)
                            .addGroup(fundo2Layout.createSequentialGroup()
                                .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 59, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(406, 406, 406))
                    .addGroup(fundo2Layout.createSequentialGroup()
                        .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecionarImagemPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fundo2Layout.createSequentialGroup()
                                .addComponent(cadastrarPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(433, Short.MAX_VALUE))))
        );
        fundo2Layout.setVerticalGroup(
            fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fundo2Layout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundo2Layout.createSequentialGroup()
                        .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoCep2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoAreaAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundo2Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundo2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26)))))
                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fundo2Layout.createSequentialGroup()
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRua2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundo2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(fundo2Layout.createSequentialGroup()
                            .addComponent(selecionarImagemPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cadastrarPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setText("Cadastrar cliente: Pessoa jurídica");

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(fundo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelFundoLayout.setVerticalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(fundo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeFantasiaActionPerformed

    private void campoNomeFantasiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeFantasiaKeyReleased

    }//GEN-LAST:event_campoNomeFantasiaKeyReleased

    private void campoCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCnpjActionPerformed

    private void campoCnpjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCnpjKeyReleased

    }//GEN-LAST:event_campoCnpjKeyReleased

    private void campoRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRazaoSocialActionPerformed

    private void campoRazaoSocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRazaoSocialKeyReleased

    }//GEN-LAST:event_campoRazaoSocialKeyReleased

    private void campoCep2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCep2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCep2KeyPressed

    private void campoCep2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCep2KeyReleased

        String cp = campoCep2.getText();
        cp = cp.replaceAll("\\D*", ""); //ignora qualquer coisa que não seja número
        int cont = cp.length();
        ViaCEP viaCep = new ViaCEP();

        if(cont==8){
            try {
                viaCep.buscar(cp);
                campoCidade2.setText(viaCep.getLocalidade());
                campoRua2.setText(viaCep.getLogradouro());
                campoUf.setSelectedItem(viaCep.getUf());
            } catch (ViaCEPException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao buscar cep"+ex);
            }
        }
    }//GEN-LAST:event_campoCep2KeyReleased

    private void campoRua2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRua2KeyReleased

    }//GEN-LAST:event_campoRua2KeyReleased

    private void campoAreaAtuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAreaAtuacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAreaAtuacaoActionPerformed

    private void campoCidade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCidade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCidade2ActionPerformed

    private void campoCidade2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCidade2KeyReleased

    }//GEN-LAST:event_campoCidade2KeyReleased

    private void campoN2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoN2KeyReleased

    }//GEN-LAST:event_campoN2KeyReleased

    private void campoTelefone2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTelefone2KeyReleased

    }//GEN-LAST:event_campoTelefone2KeyReleased

    private void selecionarImagemPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarImagemPJActionPerformed
        //Inserindo imagem no Jlabel
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagens em JPEG e PNG","jpg","png");
        jfc.addChoosableFileFilter(filtro);
        jfc.setAcceptAllFileFilterUsed(false);
        jfc.setDialogTitle("Selecionar Foto");
        boolean isPng = false;

        jfc.showOpenDialog(imagemPJ);

        if(jfc.getSelectedFile() != null)
        {
            String caminho = ""+jfc.getSelectedFile().getAbsolutePath();
            isPng = jfc.getSelectedFile().getName().endsWith("png");

            try {
                imageBuffer = ImageIO.read(new File(caminho));
                int type = BufferedImage.TYPE_INT_RGB;
                if(isPng){
                    type = BufferedImage.BITMASK;
                }

                BufferedImage redimensionarImagem = new BufferedImage(imagemPJ.getWidth(), imagemPJ.getHeight(), type);
                Graphics2D g = redimensionarImagem.createGraphics();
                g.setComposite(AlphaComposite.Src);
                g.drawImage(imageBuffer, 0, 0, imagemPJ.getWidth(), imagemPJ.getHeight(), null);

                if(isPng){
                    ImageIO.write(redimensionarImagem,"png", bytesImg);
                }
                else{
                    ImageIO.write(redimensionarImagem,"jpg", bytesImg);
                }

                bytesImg.flush();
                byteArray = bytesImg.toByteArray();
                bytesImg.close();

                Image imag = imageBuffer.getScaledInstance(imagemPJ.getWidth(), imagemPJ.getHeight(), Image.SCALE_SMOOTH);

                imagemPJ.setBorder(null);
                imagemPJ.setIcon(new ImageIcon(imag));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null,"Erro em carregar Imagem no JChosserFile \n Erro: "+ex);
            }
        }
    }//GEN-LAST:event_selecionarImagemPJActionPerformed

    private void cadastrarPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPessoaJuridicaActionPerformed

        conecta.conecta();
        pegarImagem.setImagem(byteArray);

        //insere dados no banco
        clienteJuridico.setNomeFantasia(campoNomeFantasia.getText());
        clienteJuridico.setCEP(campoCep2.getText());
        clienteJuridico.setAreaAtuacao((String) campoAreaAtuacao.getSelectedItem());
        clienteJuridico.setRazaoSocial(campoRazaoSocial.getText());
        clienteJuridico.setCNPJ(campoCnpj.getText());
        clienteJuridico.setNumero(campoN2.getText());
        clienteJuridico.setRua(campoRua2.getText());
        clienteJuridico.setCidade(campoCidade2.getText());
        clienteJuridico.setTelefone(campoTelefone2.getText());
        clienteJuridico.setUf((String) campoUf.getSelectedItem());
        clienteJuridico.setFoto(pegarImagem.getImagem());
        if(insere.inserirClienteJ(clienteJuridico)==true){

            // zera os campos depois de salvos os dados
            campoNomeFantasia.setText(null);
            campoCep2.setText(null);
            campoAreaAtuacao.setSelectedIndex(0);
            campoUf.setSelectedIndex(0);
            campoRazaoSocial.setText(null);
            campoCnpj.setText(null);
            campoN2.setText(null);
            campoRua2.setText(null);
            campoCidade2.setText(null);
            campoTelefone2.setText(null);
            campoUf.setSelectedIndex(0);
            imagemPJ.setIcon(null);
            //desativa os campos
        campoNomeFantasia.setEnabled(false);
        campoAreaAtuacao.setEnabled(false);
        campoUf.setEnabled(false);
        campoCep2.setEnabled(false);
        campoRazaoSocial.setEnabled(false);
        campoCnpj.setEnabled(false);
        campoN2.setEnabled(false);
        campoRua2.setEnabled(false);
        campoCidade2.setEnabled(false);
        campoTelefone2.setEnabled(false);
        campoUf.setEnabled(false);
        selecionarImagemPJ.setEnabled(false);
        cadastrarPessoaJuridica.setEnabled(false);
        Novo.setEnabled(true);
        }

        else{
            JOptionPane.showMessageDialog(null,"Não é possível cadastrar o cliente juridico\n"
                + "Verifique se todos os campos estão preenchidos");
        }
    }//GEN-LAST:event_cadastrarPessoaJuridicaActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        campoNomeFantasia.setEnabled(true);
        campoAreaAtuacao.setEnabled(true);
        campoCep2.setEnabled(true);
        campoRazaoSocial.setEnabled(true);
        campoCnpj.setEnabled(true);
        campoN2.setEnabled(true);
        campoRua2.setEnabled(true);
        campoCidade2.setEnabled(true);
        campoTelefone2.setEnabled(true);
        campoUf.setEnabled(true);
        selecionarImagemPJ.setEnabled(true);
        cadastrarPessoaJuridica.setEnabled(true);
        Novo.setEnabled(false);
    }//GEN-LAST:event_NovoActionPerformed

    private void campoUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUfActionPerformed

    private void campoCep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCep2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCep2ActionPerformed

    private void clientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesMouseEntered

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        ListarClientesJuridicos LCJ = new ListarClientesJuridicos();
        LCJ.setVisible(true);
    }//GEN-LAST:event_clientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarClienteJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Novo;
    private javax.swing.JButton cadastrarPessoaJuridica;
    private javax.swing.JComboBox<String> campoAreaAtuacao;
    private javax.swing.JFormattedTextField campoCep2;
    private javax.swing.JTextField campoCidade2;
    private javax.swing.JFormattedTextField campoCnpj;
    private javax.swing.JTextField campoN2;
    private javax.swing.JTextField campoNomeFantasia;
    private javax.swing.JTextField campoRazaoSocial;
    private javax.swing.JTextField campoRua2;
    private javax.swing.JFormattedTextField campoTelefone2;
    private javax.swing.JComboBox<String> campoUf;
    private javax.swing.JButton clientes;
    private javax.swing.JPanel fundo2;
    private javax.swing.JLabel imagemPJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JButton selecionarImagemPJ;
    // End of variables declaration//GEN-END:variables
}
