/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import Objetos.ModeloTabela;
import Objetos.ProcessoClienteFisico;
import Objetos.ProcessoClienteJuridico;
import br.com.parg.viacep.ViaCEP;
import br.com.parg.viacep.ViaCEPException;
import conexao.ConectaBanco;
import conexao.InsereNoBanco;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Manoel Henrique
 */
public class CadProcessoJuridico extends javax.swing.JFrame {

    /**
     * Creates new form CadProcessoFisico
     */
    
        ProcessoClienteJuridico processo = new ProcessoClienteJuridico();
        InsereNoBanco inserir = new InsereNoBanco();
    public CadProcessoJuridico() {
        initComponents();
        tabelaAdvogado.setVisible(false);
        tabelaReu.setVisible(false);
        tabelaTestemunha.setVisible(false);
        tabelaClienteJuridico.setVisible(false);
        tabelaJuiz.setVisible(false);
        
        
    }
    JScrollPane TbAdvogado;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        public void preencherTabelaAdvogado(String sql){
        ArrayList linhas = new ArrayList();
        String[] colunas = new String[]{""};
        conexao.ConectaBanco conexao = new ConectaBanco();
        conexao.conecta();
        conexao.executaSQL(sql);

        try {
          conexao.rs.first();
          
          do{
          linhas.add(new Object[]{conexao.rs.getString("nome")});
          }while(conexao.rs.next());
        } catch (SQLException ex) {
            
        }
        
        Objetos.ModeloTabela modelo = new ModeloTabela(linhas, colunas);
        tabelaAdvogado.setModel(modelo);
        tabelaAdvogado.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelaAdvogado.getColumnModel().getColumn(0).setResizable(false);
        tabelaAdvogado.getTableHeader().setReorderingAllowed(false);
        tabelaAdvogado.setAutoResizeMode(tabelaAdvogado.AUTO_RESIZE_OFF);
        tabelaAdvogado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }
        
        
    public void preencherTabelaReu(String sql){
        ArrayList linhas = new ArrayList();
        String[] colunas = new String[]{"Reu"};
        conexao.ConectaBanco conexao = new ConectaBanco();
        conexao.conecta();
        conexao.executaSQL(sql);

        try {
          conexao.rs.first();
          
          
          do{
          linhas.add(new Object[]{conexao.rs.getString("nome")});
          }while(conexao.rs.next());
        } catch (SQLException ex) {
            
        }
        
        Objetos.ModeloTabela modelo = new ModeloTabela(linhas, colunas);
        tabelaReu.setModel(modelo);
        tabelaReu.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelaReu.getColumnModel().getColumn(0).setResizable(false);
        tabelaReu.getTableHeader().setReorderingAllowed(false);
        tabelaReu.setAutoResizeMode(tabelaReu.AUTO_RESIZE_OFF);
        tabelaReu.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }
    
    
            public void preencherTabelaTestemunha(String sql){
        ArrayList linhas = new ArrayList();
        String[] colunas = new String[]{""};
        conexao.ConectaBanco conexao = new ConectaBanco();
        conexao.conecta();
        conexao.executaSQL(sql);

        try {
          conexao.rs.first();
          
          do{
          linhas.add(new Object[]{conexao.rs.getString("nome")});
          }while(conexao.rs.next());
        } catch (SQLException ex) {
            
        }
        
        Objetos.ModeloTabela modelo = new ModeloTabela(linhas, colunas);
        tabelaTestemunha.setModel(modelo);
        tabelaTestemunha.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelaTestemunha.getColumnModel().getColumn(0).setResizable(false);
        tabelaTestemunha.getTableHeader().setReorderingAllowed(false);
        tabelaTestemunha.setAutoResizeMode(tabelaTestemunha.AUTO_RESIZE_OFF);
        tabelaTestemunha.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }


    public void preencherTabelaClienteJ(String sql){
        ArrayList linhas = new ArrayList();
        String[] colunas = new String[]{""};
        conexao.ConectaBanco conexao = new ConectaBanco();
        conexao.conecta();
        conexao.executaSQL(sql);

        try {
          conexao.rs.first();
          
          do{
          linhas.add(new Object[]{conexao.rs.getString("nome_fantasia")});
          }while(conexao.rs.next());
        } catch (SQLException ex) {
            
        }
        
        Objetos.ModeloTabela modelo = new ModeloTabela(linhas, colunas);
        tabelaClienteJuridico.setModel(modelo);
        tabelaClienteJuridico.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelaClienteJuridico.getColumnModel().getColumn(0).setResizable(false);
        tabelaClienteJuridico.getTableHeader().setReorderingAllowed(false);
        tabelaClienteJuridico.setAutoResizeMode(tabelaClienteJuridico.AUTO_RESIZE_OFF);
        tabelaClienteJuridico.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }
    
    
    public void preencherTabelaJuiz(String sql){
        ArrayList linhas = new ArrayList();
        String[] colunas = new String[]{""};
        conexao.ConectaBanco conexao = new ConectaBanco();
        conexao.conecta();
        conexao.executaSQL(sql);

        try {
          conexao.rs.first();
          
          do{
          linhas.add(new Object[]{conexao.rs.getString("nome")});
          }while(conexao.rs.next());
        } catch (SQLException ex) {
            
        }
        
        Objetos.ModeloTabela modelo = new ModeloTabela(linhas, colunas);
        tabelaJuiz.setModel(modelo);
        tabelaJuiz.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelaJuiz.getColumnModel().getColumn(0).setResizable(false);
        tabelaJuiz.getTableHeader().setReorderingAllowed(false);
        tabelaJuiz.setAutoResizeMode(tabelaJuiz.AUTO_RESIZE_OFF);
        tabelaJuiz.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNumeroProcesso = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        CampoAdvogado = new javax.swing.JTextField();
        tabelaAdvogado = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        campoAssunto = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        campoReu = new javax.swing.JTextField();
        tabelaReu = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoTestemunha = new javax.swing.JTextField();
        tabelaTestemunha = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        campoClienteJuridico = new javax.swing.JTextField();
        tabelaClienteJuridico = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        campoJuiz = new javax.swing.JTextField();
        tabelaJuiz = new javax.swing.JTable();
        Novo = new javax.swing.JButton();
        CadastrarU = new javax.swing.JButton();
        importar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        campoCep = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        campoDataInicio = new javax.swing.JFormattedTextField();
        campoDocumento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoCaminho = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar processo: Cliente jurídico");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Número do processo");

        try {
            campoNumeroProcesso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-##.####.###.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoNumeroProcesso.setEnabled(false);

        jLabel5.setText("Advogado");

        CampoAdvogado.setEnabled(false);
        CampoAdvogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoAdvogadoActionPerformed(evt);
            }
        });
        CampoAdvogado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoAdvogadoKeyReleased(evt);
            }
        });

        tabelaAdvogado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaAdvogado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAdvogadoMouseClicked(evt);
            }
        });

        jLabel2.setText("Assunto");

        campoAssunto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Trabalhista" }));
        campoAssunto.setEnabled(false);

        jLabel6.setText("Réu");

        campoReu.setEnabled(false);
        campoReu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoReuActionPerformed(evt);
            }
        });
        campoReu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoReuKeyReleased(evt);
            }
        });

        tabelaReu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaReu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaReuMouseClicked(evt);
            }
        });

        jLabel3.setText("Cidade");

        campoCidade.setEnabled(false);

        jLabel7.setText("Testemunha");

        campoTestemunha.setEnabled(false);
        campoTestemunha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTestemunhaActionPerformed(evt);
            }
        });
        campoTestemunha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoTestemunhaKeyReleased(evt);
            }
        });

        tabelaTestemunha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaTestemunha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaTestemunhaMouseClicked(evt);
            }
        });

        jLabel4.setText("Cliente Jurídico");

        campoClienteJuridico.setEnabled(false);
        campoClienteJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoClienteJuridicoActionPerformed(evt);
            }
        });
        campoClienteJuridico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoClienteJuridicoKeyReleased(evt);
            }
        });

        tabelaClienteJuridico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaClienteJuridico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClienteJuridicoMouseClicked(evt);
            }
        });

        jLabel8.setText("Juíz");

        campoJuiz.setEnabled(false);
        campoJuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoJuizActionPerformed(evt);
            }
        });
        campoJuiz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoJuizKeyReleased(evt);
            }
        });

        tabelaJuiz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaJuiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaJuizMouseClicked(evt);
            }
        });

        Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/novo.png"))); // NOI18N
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });

        CadastrarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/salvar.png"))); // NOI18N
        CadastrarU.setEnabled(false);
        CadastrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarUActionPerformed(evt);
            }
        });

        importar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/importar.png"))); // NOI18N
        importar.setEnabled(false);
        importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarActionPerformed(evt);
            }
        });

        jLabel9.setText("CEP");

        try {
            campoCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCep.setEnabled(false);
        campoCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoCepKeyReleased(evt);
            }
        });

        jLabel10.setText("Data de abertura do processo");

        try {
            campoDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoDataInicio.setEnabled(false);

        campoDocumento.setEnabled(false);

        jLabel11.setText("Documento:");

        jLabel12.setText("Caminho:");

        campoCaminho.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(campoJuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNumeroProcesso)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel10)
                                            .addComponent(campoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(CampoAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel2)
                                                    .addComponent(campoAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(tabelaAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tabelaReu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoReu, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(campoCep, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(campoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(campoTestemunha, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tabelaTestemunha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CadastrarU, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(importar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(tabelaClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addComponent(tabelaJuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campoCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNumeroProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(CampoAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoReu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tabelaAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tabelaReu, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoTestemunha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(tabelaTestemunha, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(tabelaClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoJuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(tabelaJuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CadastrarU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(importar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        campoCep.setEnabled(true);
        campoNumeroProcesso.setEnabled(true);
        campoDataInicio.setEnabled(true);
        campoAssunto.setEnabled(true);
        campoCidade.setEnabled(true);
        campoClienteJuridico.setEnabled(true);
        campoJuiz.setEnabled(true);
        CampoAdvogado.setEnabled(true);
        campoTestemunha.setEnabled(true);
        campoReu.setEnabled(true);
        CadastrarU.setEnabled(true);
        importar.setEnabled(true);
        Novo.setEnabled(false);
    }//GEN-LAST:event_NovoActionPerformed

    private void CadastrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarUActionPerformed

        conexao.ConectaBanco conecta = new ConectaBanco();
        conecta.conecta();
        
        processo.setNprocesso(campoNumeroProcesso.getText());
        processo.setAssunto((String) campoAssunto.getSelectedItem());
        processo.setCep(campoCep.getText());
        processo.setAdvogado(CampoAdvogado.getText());
        processo.setCidade(campoCidade.getText());
        processo.setClienteJ(campoClienteJuridico.getText());
        processo.setJuiz(campoJuiz.getText());
        processo.setReu(campoReu.getText());
        processo.setTestemunha(campoTestemunha.getText());
        processo.setAbertura(campoDataInicio.getText());
        
        if(inserir.inserirProcessoCJ(processo)==true){
        
        campoNumeroProcesso.setText(null);
        campoCidade.setText(null);
        campoClienteJuridico.setText(null);
        campoJuiz.setText(null);
        CampoAdvogado.setText(null);
        campoTestemunha.setText(null);
        campoReu.setText(null);
        campoCep.setText(null);
        campoDataInicio.setText(null);
        campoCaminho.setText(null);
        campoDocumento.setText(null);
        
        campoCep.setEnabled(false);
        campoNumeroProcesso.setEnabled(false);
        campoAssunto.setEnabled(false);
        campoCidade.setEnabled(false);
        campoClienteJuridico.setEnabled(false);
        campoJuiz.setEnabled(false);
        CampoAdvogado.setEnabled(false);
        campoTestemunha.setEnabled(false);
        campoReu.setEnabled(false);
        CadastrarU.setEnabled(false);
        campoDataInicio.setEnabled(false);
        importar.setEnabled(false);
        Novo.setEnabled(true);
        JOptionPane.showMessageDialog(rootPane,"Dados inseridos com sucesso");
        conecta.desconecta();
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos");
        
        
        
        
    }//GEN-LAST:event_CadastrarUActionPerformed

    private void CampoAdvogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoAdvogadoActionPerformed
    
    }//GEN-LAST:event_CampoAdvogadoActionPerformed

    private void CampoAdvogadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoAdvogadoKeyReleased
    preencherTabelaAdvogado("select nome from advogado where nome ilike '%" + CampoAdvogado.getText() + "%' order by nome");
    tabelaAdvogado.setVisible(true);
    tabelaTestemunha.setVisible(false);
    tabelaClienteJuridico.setVisible(false);
    tabelaJuiz.setVisible(false);
    tabelaReu.setVisible(false);
    }//GEN-LAST:event_CampoAdvogadoKeyReleased

    private void tabelaAdvogadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAdvogadoMouseClicked
        CampoAdvogado.setText(tabelaAdvogado.getValueAt(tabelaAdvogado.getSelectedRow(), 0).toString());
        tabelaAdvogado.setVisible(false);
    }//GEN-LAST:event_tabelaAdvogadoMouseClicked

    private void tabelaReuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaReuMouseClicked
        campoReu.setText(tabelaReu.getValueAt(tabelaReu.getSelectedRow(), 0).toString());
        tabelaReu.setVisible(false);
    }//GEN-LAST:event_tabelaReuMouseClicked

    private void campoTestemunhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTestemunhaActionPerformed

    }//GEN-LAST:event_campoTestemunhaActionPerformed

    private void campoTestemunhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTestemunhaKeyReleased
    preencherTabelaTestemunha("select nome from testemunha where nome ilike '%" + campoTestemunha.getText() + "%' order by nome");
    tabelaTestemunha.setVisible(true);
    tabelaAdvogado.setVisible(false);
    tabelaClienteJuridico.setVisible(false);
    tabelaJuiz.setVisible(false);
    tabelaReu.setVisible(false);
    }//GEN-LAST:event_campoTestemunhaKeyReleased

    private void tabelaClienteJuridicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClienteJuridicoMouseClicked
        campoClienteJuridico.setText(tabelaClienteJuridico.getValueAt(tabelaClienteJuridico.getSelectedRow(), 0).toString());
        tabelaClienteJuridico.setVisible(false);
    }//GEN-LAST:event_tabelaClienteJuridicoMouseClicked

    private void tabelaJuizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaJuizMouseClicked
        campoJuiz.setText(tabelaJuiz.getValueAt(tabelaJuiz.getSelectedRow(), 0).toString());
        tabelaJuiz.setVisible(false);
    }//GEN-LAST:event_tabelaJuizMouseClicked

    private void campoReuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoReuKeyReleased
    preencherTabelaReu("select nome from reu_pessoa_fisica where nome ilike '%" + campoReu.getText() + "%' order by nome");
    tabelaReu.setVisible(true);
    tabelaTestemunha.setVisible(false);
    tabelaAdvogado.setVisible(false);
    tabelaClienteJuridico.setVisible(false);
    tabelaJuiz.setVisible(false);
    }//GEN-LAST:event_campoReuKeyReleased

    private void campoClienteJuridicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoClienteJuridicoKeyReleased
    preencherTabelaClienteJ("select nome_fantasia from cliente_pessoa_juridica where nome_fantasia ilike '%" + campoClienteJuridico.getText() + "%' order by nome_fantasia");
    tabelaClienteJuridico.setVisible(true);
    tabelaTestemunha.setVisible(false);
    tabelaAdvogado.setVisible(false);
    tabelaJuiz.setVisible(false);
    tabelaReu.setVisible(false);
    }//GEN-LAST:event_campoClienteJuridicoKeyReleased

    private void tabelaTestemunhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaTestemunhaMouseClicked
        campoTestemunha.setText(tabelaTestemunha.getValueAt(tabelaTestemunha.getSelectedRow(), 0).toString());
        tabelaTestemunha.setVisible(false);

    }//GEN-LAST:event_tabelaTestemunhaMouseClicked

    private void campoJuizKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoJuizKeyReleased
    preencherTabelaJuiz("select nome from juiz where nome ilike '%" + campoJuiz.getText() + "%' order by nome");
    tabelaJuiz.setVisible(true);
    tabelaTestemunha.setVisible(false);
    tabelaAdvogado.setVisible(false);
    tabelaClienteJuridico.setVisible(false);
    tabelaReu.setVisible(false);
    }//GEN-LAST:event_campoJuizKeyReleased

    private void importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarActionPerformed
        JFileChooser Arquivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Arquivos pdf e docx","pdf", "docx");
        Arquivo.addChoosableFileFilter(filtro);
        Arquivo.setAcceptAllFileFilterUsed(false);
        int opc = Arquivo.showOpenDialog(this);
        
        if(opc==JFileChooser.APPROVE_OPTION){
        String nomeArqivo = Arquivo.getSelectedFile().getName();
        String caminhoArquivo = Arquivo.getSelectedFile().toString();
        
        campoDocumento.setText(nomeArqivo);
        campoCaminho.setText(caminhoArquivo);
        
        }
    }//GEN-LAST:event_importarActionPerformed

    private void campoReuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoReuActionPerformed
        
    }//GEN-LAST:event_campoReuActionPerformed

    private void campoClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoClienteJuridicoActionPerformed

    }//GEN-LAST:event_campoClienteJuridicoActionPerformed

    private void campoJuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoJuizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoJuizActionPerformed

    private void campoCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCepKeyReleased
        String cp = campoCep.getText();
        cp = cp.replaceAll("\\D*", ""); //ignora qualquer coisa que não seja número
        int cont = cp.length();
        ViaCEP viaCep = new ViaCEP();

        if(cont==8){
            try {
                viaCep.buscar(cp);
                campoCidade.setText(viaCep.getLocalidade());
            } catch (ViaCEPException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao buscar cep, certifique se o cep está correto");
            }
        }
    }//GEN-LAST:event_campoCepKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProcessoJuridico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProcessoJuridico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProcessoJuridico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProcessoJuridico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProcessoJuridico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarU;
    private javax.swing.JTextField CampoAdvogado;
    private javax.swing.JButton Novo;
    private javax.swing.JComboBox<String> campoAssunto;
    private javax.swing.JTextField campoCaminho;
    private javax.swing.JFormattedTextField campoCep;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoClienteJuridico;
    private javax.swing.JFormattedTextField campoDataInicio;
    private javax.swing.JTextField campoDocumento;
    private javax.swing.JTextField campoJuiz;
    private javax.swing.JFormattedTextField campoNumeroProcesso;
    private javax.swing.JTextField campoReu;
    private javax.swing.JTextField campoTestemunha;
    private javax.swing.JButton importar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelaAdvogado;
    private javax.swing.JTable tabelaClienteJuridico;
    private javax.swing.JTable tabelaJuiz;
    private javax.swing.JTable tabelaReu;
    private javax.swing.JTable tabelaTestemunha;
    // End of variables declaration//GEN-END:variables
}
