/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import Objetos.ModeloTabela;
import conexao.ConectaBanco;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Manoel Henrique
 */
public class ListarProcessoF extends javax.swing.JFrame {

    /**
     * Creates new form ListarProcessoF
     */
    conexao.ConectaBanco conexao = new ConectaBanco();
    public ListarProcessoF() {
        initComponents();
        preencherTabela("select numero, assunto, cep, cidade, cliente_fisico, advogado, juiz, testemunha, reu_pessoa_juridica, abertura, arquivamento, causa from processos_fisicos;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        public void preencherTabela(String sql){
        ArrayList linhas = new ArrayList();
        String[] colunas = new String[]{"Nº ", "Assunto", "CEP", "Cidade", "Cliente fisíco", "Advogado", "Juiz", "Testemunha", "Réu", "Abertura", "Arquivamento", "Causa"};
        conexao.conecta();
        conexao.executaSQL(sql);

        try {
          conexao.rs.first();
          do{
          linhas.add(new Object[]{conexao.rs.getString("numero"), conexao.rs.getString("assunto"), conexao.rs.getString("cep"), conexao.rs.getString("cidade"), conexao.rs.getString("cliente_fisico"), conexao.rs.getString("advogado"), conexao.rs.getString("juiz"), conexao.rs.getString("testemunha"), conexao.rs.getString("reu_pessoa_juridica"), conexao.rs.getString("abertura"), conexao.rs.getString("arquivamento"), conexao.rs.getString("causa")});
          }while(conexao.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro");
        }
        
        Objetos.ModeloTabela modelo = new ModeloTabela(linhas, colunas);
        tabelaProcessoF.setModel(modelo);
        tabelaProcessoF.getColumnModel().getColumn(0).setPreferredWidth(180);
        tabelaProcessoF.getColumnModel().getColumn(0).setResizable(false);
        tabelaProcessoF.getColumnModel().getColumn(1).setPreferredWidth(80);
        tabelaProcessoF.getColumnModel().getColumn(1).setResizable(false);
        tabelaProcessoF.getColumnModel().getColumn(2).setPreferredWidth(75);
        tabelaProcessoF.getColumnModel().getColumn(2).setResizable(false);
        tabelaProcessoF.getColumnModel().getColumn(3).setPreferredWidth(120);
        tabelaProcessoF.getColumnModel().getColumn(3).setResizable(false);
        tabelaProcessoF.getColumnModel().getColumn(4).setPreferredWidth(270);
        tabelaProcessoF.getColumnModel().getColumn(4).setResizable(false);
        tabelaProcessoF.getColumnModel().getColumn(5).setPreferredWidth(270);
        tabelaProcessoF.getColumnModel().getColumn(5).setResizable(false);
        tabelaProcessoF.getColumnModel().getColumn(6).setPreferredWidth(270);
        tabelaProcessoF.getColumnModel().getColumn(6).setResizable(false);
        tabelaProcessoF.getColumnModel().getColumn(7).setPreferredWidth(270);
        tabelaProcessoF.getColumnModel().getColumn(7).setResizable(false);
        tabelaProcessoF.getColumnModel().getColumn(8).setPreferredWidth(270);
        tabelaProcessoF.getColumnModel().getColumn(8).setResizable(false);
        tabelaProcessoF.getColumnModel().getColumn(9).setPreferredWidth(85);
        tabelaProcessoF.getColumnModel().getColumn(9).setResizable(false);
        tabelaProcessoF.getColumnModel().getColumn(10).setPreferredWidth(85);
        tabelaProcessoF.getColumnModel().getColumn(10).setResizable(false);
        tabelaProcessoF.getColumnModel().getColumn(11).setPreferredWidth(80);
        tabelaProcessoF.getColumnModel().getColumn(11).setResizable(false);
        tabelaProcessoF.getTableHeader().setReorderingAllowed(false);
        tabelaProcessoF.setAutoResizeMode(tabelaProcessoF.AUTO_RESIZE_OFF);
        tabelaProcessoF.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProcessoF = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Processos físicos");
        setResizable(false);

        tabelaProcessoF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabelaProcessoF.setForeground(new java.awt.Color(255, 204, 0));
        tabelaProcessoF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaProcessoF);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarProcessoF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarProcessoF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarProcessoF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarProcessoF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarProcessoF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProcessoF;
    // End of variables declaration//GEN-END:variables
}
