/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import JInternalFrames.JInternaltelaPrincipal;


/**
 *
 * @author Manoel Henrique
 */
public class TelaPrincipal extends javax.swing.JFrame {

//    /**
//     * Creates new form TelaPrincipal
//     */
//    
//   // BufferedImage foto;
//    //Image img;
//     BufferedImage imageBuffer = null;
//     ByteArrayOutputStream bytesImg = new ByteArrayOutputStream();
//     byte[] byteArray;
//     
//     //telas
//     
//     cadastroClienteF clienteFisico = new cadastroClienteF();
//     cadastroClienteJ clienteJuridico = new cadastroClienteJ();
//     
//    
//    
//    conexao.ConectaBanco conexao = new ConectaBanco();
//    InsereNoBanco inserir = new InsereNoBanco();
    
    JInternalFrames.JInternaltelaPrincipal fundoTela = new JInternaltelaPrincipal();
    
    public TelaPrincipal() {
        
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        
        try {
            fundo.add(fundoTela);
            fundoTela.setVisible(true);
            fundoTela.setMaximum(true);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        

            
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio = new javax.swing.JPanel();
        fundo = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuItemPessoaFisica = new javax.swing.JMenuItem();
        menuItemPessoaJuridica = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemPessoaFisica1 = new javax.swing.JMenuItem();
        menuItemPessoaJuridica1 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemExcluirClientes = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuJuizes = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        menuTestemunhas = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        menuAgendamentos = new javax.swing.JMenu();
        itemNovoAgendamento = new javax.swing.JMenuItem();
        itemAudienciasA = new javax.swing.JMenuItem();
        itemReunioesA = new javax.swing.JMenuItem();
        itemPrioridades = new javax.swing.JMenuItem();
        menuProcessos = new javax.swing.JMenu();
        itemCadastrarProcesso = new javax.swing.JMenu();
        CadProcessoFisico = new javax.swing.JMenuItem();
        CadProcessoJuridico = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ListaProcessoFisico = new javax.swing.JMenuItem();
        ListaProcessoJuridico = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ArquivarProcessoFisico = new javax.swing.JMenuItem();
        ArquivarProcessoJuridico = new javax.swing.JMenuItem();
        itemExcluirProcesso = new javax.swing.JMenuItem();
        itemProcessosArquivados = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        itemNovoUsuario = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        itemEditarUsuario = new javax.swing.JMenuItem();
        itemExcluirUsuario = new javax.swing.JMenuItem();
        itemSair = new javax.swing.JMenuItem();

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MH advocacia");

        fundo.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cliente.png"))); // NOI18N
        menuClientes.setText("Clientes");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/add cliente.jpg"))); // NOI18N
        jMenu1.setText("Adicionar cliente");

        menuItemPessoaFisica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pessoa_fisica.png"))); // NOI18N
        menuItemPessoaFisica.setText("Pessoa física");
        menuItemPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPessoaFisicaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemPessoaFisica);

        menuItemPessoaJuridica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pessoa_juridica.png"))); // NOI18N
        menuItemPessoaJuridica.setText("Pessoa júridica");
        menuItemPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPessoaJuridicaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemPessoaJuridica);

        menuClientes.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/list cliente.jpg"))); // NOI18N
        jMenu2.setText("Listar clientes");

        menuItemPessoaFisica1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pessoa_fisica.png"))); // NOI18N
        menuItemPessoaFisica1.setText("Pessoa física");
        menuItemPessoaFisica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPessoaFisica1ActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemPessoaFisica1);

        menuItemPessoaJuridica1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pessoa_juridica.png"))); // NOI18N
        menuItemPessoaJuridica1.setText("Pessoa júridica");
        menuItemPessoaJuridica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPessoaJuridica1ActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemPessoaJuridica1);

        menuClientes.add(jMenu2);

        jMenuItem1.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/edite cliente.jpg"))); // NOI18N
        jMenuItem1.setText("Editar cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuClientes.add(jMenuItem1);

        itemExcluirClientes.setForeground(new java.awt.Color(255, 0, 0));
        itemExcluirClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/delete cliente.jpg"))); // NOI18N
        itemExcluirClientes.setText("Excluir clientes");
        itemExcluirClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExcluirClientesActionPerformed(evt);
            }
        });
        menuClientes.add(itemExcluirClientes);

        jMenuItem2.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/seach cliente.jpg"))); // NOI18N
        jMenuItem2.setText("Buscar cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuClientes.add(jMenuItem2);

        jMenuBar2.add(menuClientes);

        menuJuizes.setForeground(new java.awt.Color(255, 0, 0));
        menuJuizes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/judge.png"))); // NOI18N
        menuJuizes.setText("Juizes");

        jMenuItem5.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/add judge.jpg"))); // NOI18N
        jMenuItem5.setText("Adicionar juiz");
        menuJuizes.add(jMenuItem5);

        jMenuItem6.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/edite judge.jpg"))); // NOI18N
        jMenuItem6.setText("Editar juiz");
        menuJuizes.add(jMenuItem6);

        jMenuItem8.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/list judge.jpg"))); // NOI18N
        jMenuItem8.setText("Listar juizes");
        menuJuizes.add(jMenuItem8);

        jMenuItem7.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/delete judge.jpg"))); // NOI18N
        jMenuItem7.setText("Excluir juiz");
        menuJuizes.add(jMenuItem7);

        jMenuBar2.add(menuJuizes);

        menuTestemunhas.setForeground(new java.awt.Color(255, 0, 0));
        menuTestemunhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/testemunha.png"))); // NOI18N
        menuTestemunhas.setText("Testemunhas");

        jMenuItem9.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/add testemunha.jpg"))); // NOI18N
        jMenuItem9.setText("Adicionar  testemunha");
        menuTestemunhas.add(jMenuItem9);

        jMenuItem10.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/edite testemunha.jpg"))); // NOI18N
        jMenuItem10.setText("Editar testemunha");
        menuTestemunhas.add(jMenuItem10);

        jMenuItem11.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/delete testemunha.jpg"))); // NOI18N
        jMenuItem11.setText("Excluir testemunha");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menuTestemunhas.add(jMenuItem11);

        jMenuBar2.add(menuTestemunhas);

        jMenu3.setForeground(new java.awt.Color(255, 0, 0));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lawyer.png"))); // NOI18N
        jMenu3.setText("Advogados");

        jMenuItem12.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/add lawyer.jpg"))); // NOI18N
        jMenuItem12.setText("Adicionar advogado");
        jMenu3.add(jMenuItem12);

        jMenuItem14.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/edite lawyer.jpg"))); // NOI18N
        jMenuItem14.setText("Editar advogado");
        jMenu3.add(jMenuItem14);

        jMenuItem16.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/edite lawyer.jpg"))); // NOI18N
        jMenuItem16.setText("Listar advogados");
        jMenu3.add(jMenuItem16);

        jMenuItem15.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/delete lawyer.jpg"))); // NOI18N
        jMenuItem15.setText("Excluir advogado");
        jMenu3.add(jMenuItem15);

        jMenuBar2.add(jMenu3);

        menuAgendamentos.setForeground(new java.awt.Color(255, 0, 0));
        menuAgendamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/agendamento.png"))); // NOI18N
        menuAgendamentos.setText("Agendamentos");

        itemNovoAgendamento.setForeground(new java.awt.Color(255, 0, 0));
        itemNovoAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Pacote de Icones/icons 1/calendar_add.png"))); // NOI18N
        itemNovoAgendamento.setText("Novo agendamento");
        itemNovoAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNovoAgendamentoActionPerformed(evt);
            }
        });
        menuAgendamentos.add(itemNovoAgendamento);

        itemAudienciasA.setForeground(new java.awt.Color(255, 0, 0));
        itemAudienciasA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Pacote de Icones/icons 1/group_link.png"))); // NOI18N
        itemAudienciasA.setText("Audiências");
        menuAgendamentos.add(itemAudienciasA);

        itemReunioesA.setForeground(new java.awt.Color(255, 0, 0));
        itemReunioesA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Pacote de Icones/icons 1/group_gear.png"))); // NOI18N
        itemReunioesA.setText("Reuniões");
        itemReunioesA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReunioesAActionPerformed(evt);
            }
        });
        menuAgendamentos.add(itemReunioesA);

        itemPrioridades.setForeground(new java.awt.Color(255, 0, 0));
        itemPrioridades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Pacote de Icones/icons 1/exclamation.png"))); // NOI18N
        itemPrioridades.setText("Prioridades");
        itemPrioridades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPrioridadesActionPerformed(evt);
            }
        });
        menuAgendamentos.add(itemPrioridades);

        jMenuBar2.add(menuAgendamentos);

        menuProcessos.setForeground(new java.awt.Color(255, 0, 0));
        menuProcessos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/processo.png"))); // NOI18N
        menuProcessos.setText("Processos");

        itemCadastrarProcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/add Processo.jpg"))); // NOI18N
        itemCadastrarProcesso.setText("Cadastrar processo");

        CadProcessoFisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pessoa_fisica.png"))); // NOI18N
        CadProcessoFisico.setText("Cliente Físico");
        CadProcessoFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadProcessoFisicoActionPerformed(evt);
            }
        });
        itemCadastrarProcesso.add(CadProcessoFisico);

        CadProcessoJuridico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pessoa_juridica.png"))); // NOI18N
        CadProcessoJuridico.setText("Cliente Jurídico");
        CadProcessoJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadProcessoJuridicoActionPerformed(evt);
            }
        });
        itemCadastrarProcesso.add(CadProcessoJuridico);

        menuProcessos.add(itemCadastrarProcesso);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/list Processo.jpg"))); // NOI18N
        jMenu4.setText("Listar processo");

        ListaProcessoFisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pessoa_fisica.png"))); // NOI18N
        ListaProcessoFisico.setText("Todos os processos físicos");
        ListaProcessoFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaProcessoFisicoActionPerformed(evt);
            }
        });
        jMenu4.add(ListaProcessoFisico);

        ListaProcessoJuridico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pessoa_juridica.png"))); // NOI18N
        ListaProcessoJuridico.setText("Todos os processos jurídicos");
        ListaProcessoJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaProcessoJuridicoActionPerformed(evt);
            }
        });
        jMenu4.add(ListaProcessoJuridico);

        menuProcessos.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/arquivar Processo.jpg"))); // NOI18N
        jMenu5.setText("Arquivar processo");

        ArquivarProcessoFisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pessoa_fisica.png"))); // NOI18N
        ArquivarProcessoFisico.setText("Todos os processos físicos");
        ArquivarProcessoFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArquivarProcessoFisicoActionPerformed(evt);
            }
        });
        jMenu5.add(ArquivarProcessoFisico);

        ArquivarProcessoJuridico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pessoa_juridica.png"))); // NOI18N
        ArquivarProcessoJuridico.setText("Todos os processos jurídicos");
        ArquivarProcessoJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArquivarProcessoJuridicoActionPerformed(evt);
            }
        });
        jMenu5.add(ArquivarProcessoJuridico);

        menuProcessos.add(jMenu5);

        itemExcluirProcesso.setForeground(new java.awt.Color(255, 0, 0));
        itemExcluirProcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/delete Processo.jpg"))); // NOI18N
        itemExcluirProcesso.setText("Excluir processo");
        menuProcessos.add(itemExcluirProcesso);

        itemProcessosArquivados.setForeground(new java.awt.Color(255, 0, 0));
        itemProcessosArquivados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Pacote de Icones/icons 1/page_white_zip.png"))); // NOI18N
        itemProcessosArquivados.setText("Processos arquivados");
        menuProcessos.add(itemProcessosArquivados);

        jMenuBar2.add(menuProcessos);

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/users.png"))); // NOI18N
        menuUsuarios.setText("Usuários");

        itemNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/addUsers.jpg"))); // NOI18N
        itemNovoUsuario.setText("Novo usuário");
        itemNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNovoUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemNovoUsuario);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/listUsers.jpg"))); // NOI18N
        jMenuItem3.setText("Listar usuários");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuUsuarios.add(jMenuItem3);

        itemEditarUsuario.setForeground(new java.awt.Color(255, 0, 0));
        itemEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/EditeUsers.jpg"))); // NOI18N
        itemEditarUsuario.setText("Editar usuário");
        menuUsuarios.add(itemEditarUsuario);

        itemExcluirUsuario.setForeground(new java.awt.Color(255, 0, 0));
        itemExcluirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/deleteUsers.jpg"))); // NOI18N
        itemExcluirUsuario.setText("Excluir usuário");
        menuUsuarios.add(itemExcluirUsuario);

        itemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/sair2.png"))); // NOI18N
        itemSair.setText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemSair);

        jMenuBar2.add(menuUsuarios);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNovoUsuarioActionPerformed
        CadastrarUsuario CadUsuario = new CadastrarUsuario();
        CadUsuario.setVisible(true);
    }//GEN-LAST:event_itemNovoUsuarioActionPerformed

    private void itemReunioesAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReunioesAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemReunioesAActionPerformed

    private void itemExcluirClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExcluirClientesActionPerformed

    }//GEN-LAST:event_itemExcluirClientesActionPerformed

    private void itemNovoAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNovoAgendamentoActionPerformed

        
    }//GEN-LAST:event_itemNovoAgendamentoActionPerformed

    private void menuItemPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPessoaFisicaActionPerformed
    CadastrarClienteF cf = new CadastrarClienteF();
    cf.setVisible(true);
    }//GEN-LAST:event_menuItemPessoaFisicaActionPerformed

    private void menuItemPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPessoaJuridicaActionPerformed
         CadastrarClienteJ cj = new CadastrarClienteJ();
         cj.setVisible(true);
       
    }//GEN-LAST:event_menuItemPessoaJuridicaActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ListarUsuarios LU = new ListarUsuarios();
        LU.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuItemPessoaFisica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPessoaFisica1ActionPerformed
        ListarClientesFisicos LCF = new ListarClientesFisicos();
        LCF.setVisible(true);
    }//GEN-LAST:event_menuItemPessoaFisica1ActionPerformed

    private void menuItemPessoaJuridica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPessoaJuridica1ActionPerformed
        ListarClientesJuridicos LCJ = new ListarClientesJuridicos();
        LCJ.setVisible(true);
    }//GEN-LAST:event_menuItemPessoaJuridica1ActionPerformed

    private void CadProcessoFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadProcessoFisicoActionPerformed
        CadProcessoFisico CPCF = new CadProcessoFisico();
        CPCF.setVisible(true);
    }//GEN-LAST:event_CadProcessoFisicoActionPerformed

    private void CadProcessoJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadProcessoJuridicoActionPerformed
        CadProcessoJuridico CPCJ = new CadProcessoJuridico();
        CPCJ.setVisible(true);
    }//GEN-LAST:event_CadProcessoJuridicoActionPerformed

    private void ListaProcessoFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaProcessoFisicoActionPerformed
        ListarProcessoF LPF = new ListarProcessoF();
        LPF.setVisible(true);
    }//GEN-LAST:event_ListaProcessoFisicoActionPerformed

    private void ListaProcessoJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaProcessoJuridicoActionPerformed
        ListarProcessoJ LPJ = new ListarProcessoJ();
        LPJ.setVisible(true);
    }//GEN-LAST:event_ListaProcessoJuridicoActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void itemPrioridadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPrioridadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPrioridadesActionPerformed

    private void ArquivarProcessoFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArquivarProcessoFisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArquivarProcessoFisicoActionPerformed

    private void ArquivarProcessoJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArquivarProcessoJuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArquivarProcessoJuridicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ArquivarProcessoFisico;
    private javax.swing.JMenuItem ArquivarProcessoJuridico;
    private javax.swing.JMenuItem CadProcessoFisico;
    private javax.swing.JMenuItem CadProcessoJuridico;
    private javax.swing.JMenuItem ListaProcessoFisico;
    private javax.swing.JMenuItem ListaProcessoJuridico;
    private javax.swing.JDesktopPane fundo;
    private javax.swing.JPanel inicio;
    private javax.swing.JMenuItem itemAudienciasA;
    private javax.swing.JMenu itemCadastrarProcesso;
    private javax.swing.JMenuItem itemEditarUsuario;
    private javax.swing.JMenuItem itemExcluirClientes;
    private javax.swing.JMenuItem itemExcluirProcesso;
    private javax.swing.JMenuItem itemExcluirUsuario;
    private javax.swing.JMenuItem itemNovoAgendamento;
    private javax.swing.JMenuItem itemNovoUsuario;
    private javax.swing.JMenuItem itemPrioridades;
    private javax.swing.JMenuItem itemProcessosArquivados;
    private javax.swing.JMenuItem itemReunioesA;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuAgendamentos;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenuItem menuItemPessoaFisica;
    private javax.swing.JMenuItem menuItemPessoaFisica1;
    private javax.swing.JMenuItem menuItemPessoaJuridica;
    private javax.swing.JMenuItem menuItemPessoaJuridica1;
    private javax.swing.JMenu menuJuizes;
    private javax.swing.JMenu menuProcessos;
    private javax.swing.JMenu menuTestemunhas;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables

}
